"""
main.py
-------
FastAPI application entrypoint for JD Analytics backend.

Run with:
    uvicorn app.main:app --reload
"""

import logging

from fastapi import FastAPI, HTTPException, Request, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from app.config import settings
from app.models.response_model import ErrorResponse
from app.routers import upload

# --------------------------------------------------------------------------
# Logging
# --------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)
logger = logging.getLogger("jd_analytics.main")

# --------------------------------------------------------------------------
# FastAPI app
# --------------------------------------------------------------------------
app = FastAPI(
    title="JD Analytics API",
    description=(
        "Upload a Job Description (PDF or DOCX) and receive structured "
        "analytics generated by Google Gemini 2.5 Flash."
    ),
    version="1.0.0",
)

# --------------------------------------------------------------------------
# CORS - allow the React (Vite) frontend to call this API from the browser.
# --------------------------------------------------------------------------
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --------------------------------------------------------------------------
# Routers
# --------------------------------------------------------------------------
app.include_router(upload.router)


# --------------------------------------------------------------------------
# Startup: fail fast if configuration is invalid (e.g. missing API key).
# --------------------------------------------------------------------------
@app.on_event("startup")
async def on_startup() -> None:
    settings.validate()
    logger.info("JD Analytics backend started. Gemini model: %s", settings.GEMINI_MODEL)


# --------------------------------------------------------------------------
# Global exception handlers
#
# These ensure every error response — even ones not explicitly raised
# as HTTPException in a route — follows the same ErrorResponse shape.
# --------------------------------------------------------------------------
@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException) -> JSONResponse:
    return JSONResponse(
        status_code=exc.status_code,
        content=ErrorResponse(error=str(exc.detail)).model_dump(),
    )


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    logger.exception("Unhandled exception during request: %s %s", request.method, request.url)
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content=ErrorResponse(
            error="Internal server error.",
            detail=str(exc),
        ).model_dump(),
    )


# --------------------------------------------------------------------------
# Health check
# --------------------------------------------------------------------------
@app.get("/", tags=["Health"], summary="Health check")
async def root() -> dict:
    """Simple health check / welcome endpoint."""
    return {
        "service": "JD Analytics API",
        "status": "ok",
        "docs": "/docs",
    }


@app.get("/health", tags=["Health"], summary="Health check")
async def health() -> dict:
    """Explicit health check endpoint for uptime monitors."""
    return {"status": "ok"}
